import libtcodpy as tcod
SCREEN_SIZE = 60, 25
(SCREEN_WIDTH, SCREEN_HEIGHT) = SCREEN_SIZE
MAX_FPS = 30
CONWAY_SPEED = 1
GAME_TITLE = "Conway's Game of Pong"
PLAYER_COLORS = [tcod.red, tcod.blue]
CONWAY_COLOR = False
CONWAY_SIZE = (25, 25)
PADDLE_SIZE = 3
VERSION = "1.0"
